In [25]:
import pandas as pd
from src.models.model1.recommend import build_new_group_profile
from src.data.build_features_3 import build_feature_interaction_frequency
from sklearn.preprocessing import StandardScaler

In [26]:
test_data = pd.read_pickle ('data/test/m06c_1_1_test_data.pkl')
group_features = pd.read_pickle ('data/processed/model1/processed_group_features.pkl')
train_labels =pd.read_pickle ('data/processed/model1/processed_train_labels.pkl')
y_cleaned = pd.read_pickle ('data/interim/y_cleaned.pkl')

In [31]:
y_cleaned = pd.read_pickle ('data/interim/y_cleaned.pkl')
y_cleaned

      group_ID technique_ID  label
0        G0099    T1548.002    0.0
1        G0099        T1134    0.0
2        G0099    T1134.002    0.0
3        G0099    T1134.001    0.0
4        G0099        T1531    0.0
...        ...          ...    ...
52763    G0045    T1102.002    0.0
52764    G0045    T1102.001    0.0
52765    G0045    T1102.003    0.0
52766    G0045        T1047    1.0
52767    G0045        T1220    0.0

[52768 rows x 3 columns]

1. Interaction rate: recalculate original (not normalized) values.

In [27]:
group_features = build_feature_interaction_frequency (label_df= train_labels,
                                                      feature_df= group_features, 
                                                      object_ID= 'group_ID', 
                                                      feature_name = 'original_group_interaction_rate', 
                                                      normalize= False)
group_features

,group_ID,input_group_software_id,input_group_description,input_group_interaction_rate,input_group_tactics,original_group_interaction_rate
0,G0099,[other],"[-0.41692165, -0.26227784, -0.47415727, 0.0276...",-0.924954,[],0.0
1,G0006,"[s0025, s0119, s0026, s0121, s0002, s0039, s01...","[-0.6153141, 0.07517785, -0.5039633, -0.243659...",0.105041,"[discovery, resource_development, collection, ...",48.0
2,G0005,"[s0040, s0015, s0003]","[-0.32223642, 0.029669948, -0.7427179, -0.0198...",-0.924954,[],0.0
3,G0023,[s0064],"[-0.39972576, -0.06616345, -0.55075675, -0.038...",-0.924954,[],0.0
4,G0025,[s0069],"[-0.608141, -0.007160956, -0.7598587, 0.167140...",-0.924954,[],0.0
...,...,...,...,...,...,...
131,G0044,"[s0013, other]","[-0.3997315, 0.011453139, -0.5749509, -0.17962...",-0.924954,[],0.0
132,G0102,"[s0552, s0534, s0521, s0154, s0363, s0632, s00...","[-0.27592593, -0.100573234, -0.37286678, -0.02...",1.135036,"[discovery, collection, credential_access, com...",0.0
133,G0128,[],"[-0.48862642, -0.18858606, -0.5323841, -0.0883...",0.239388,"[resource_development, resource_development, p...",54.0
134,G0018,"[s0039, s0012, s0096, s0100, s0104, other]","[-0.2925966, 0.0350828, -0.64397854, 0.130665,...",-0.387565,"[discovery, execution, execution, discovery, d...",24.0
135,G0045,"[s0552, s0154, s0357, s0002, s0039, s0097, s00...","[-0.73226637, -0.113698326, -1.0054364, -0.120...",1.179819,"[discovery, resource_development, collection, ...",115.0

In [28]:
scaler = StandardScaler()
scaler.fit (group_features[['input_group_interaction_rate']])
original_values = scaler.inverse_transform(group_features[['input_group_interaction_rate']])
original_values

array([[-0.92495409],
       [ 0.10504107],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [-0.38756531],
       [ 0.01547627],
       [ 2.92633216],
       [ 1.49329541],
       [ 1.00068903],
       [-0.92495409],
       [ 2.56807297],
       [ 0.46330025],
       [ 0.37373546],
       [ 1.00068903],
       [ 1.40373062],
       [ 1.7619898 ],
       [-0.92495409],
       [-0.38756531],
       [-0.92495409],
       [-0.25321812],
       [-0.20843572],
       [-0.20843572],
       [ 0.86634184],
       [-0.25321812],
       [-0.92495409],
       [-0.29800052],
       [ 0.06025867],
       [-0.92495409],
       [-0.92495409],
       [ 1.7172074 ],
       [-0.92495409],
       [ 0.59764745],
       [-0.07408853],
       [-0.92495409],
       [-0.38756531],
       [-0.92495409],
       [-0.47713011],
       [ 0.14982346],
       [-0.47713011],
       [-0.92495409],
       [ 1.58286021],
       [-0.25321812],
       [ 1.04547143],
       [-0.92495409],
       [-0.02930613],
       [-0.92495409],
       [-0.43234771],
       [-0.43234771],
       [-0.38756531],
       [-0.43234771],
       [ 0.86634184],
       [ 0.86634184],
       [ 0.41851785],
       [-0.92495409],
       [ 0.91112424],
       [ 0.46330025],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [ 1.22460102],
       [-0.20843572],
       [-0.92495409],
       [ 0.46330025],
       [ 0.64242985],
       [ 0.23938826],
       [ 0.06025867],
       [-0.92495409],
       [-0.07408853],
       [ 1.09025383],
       [ 3.06067935],
       [ 0.77677704],
       [ 3.15024415],
       [-0.02930613],
       [-0.16365332],
       [ 1.04547143],
       [-0.92495409],
       [ 0.32895306],
       [-0.43234771],
       [ 2.52329057],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [-0.20843572],
       [-0.38756531],
       [ 1.7172074 ],
       [ 1.04547143],
       [-0.92495409],
       [-0.29800052],
       [-0.92495409],
       [ 1.58286021],
       [-0.92495409],
       [-0.43234771],
       [-0.92495409],
       [-0.43234771],
       [ 0.86634184],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [ 0.68721224],
       [ 2.07546659],
       [-0.92495409],
       [-0.20843572],
       [ 0.41851785],
       [ 0.32895306],
       [-0.34278292],
       [-0.92495409],
       [-0.92495409],
       [-0.20843572],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [ 0.59764745],
       [-0.29800052],
       [-0.16365332],
       [ 1.49329541],
       [-0.92495409],
       [-0.92495409],
       [ 1.62764261],
       [-0.92495409],
       [-0.25321812],
       [-0.29800052],
       [ 0.82155944],
       [ 2.03068419],
       [-0.92495409],
       [-0.43234771],
       [-0.92495409],
       [-0.92495409],
       [-0.07408853],
       [-0.92495409],
       [ 1.13503623],
       [ 0.23938826],
       [-0.38756531],
       [ 1.17981863]])

In [15]:
scaler = StandardScaler ()
group_features ['original_group_interaction_rate'] = scaler.fit_transform (group_features[['original_group_interaction_rate']])

In [16]:
group_features

,group_ID,input_group_software_id,input_group_description,input_group_interaction_rate,input_group_tactics,original_group_interaction_rate
0,G0099,[other],"[-0.41692165, -0.26227784, -0.47415727, 0.0276...",-0.924954,[],-0.736860
1,G0006,"[s0025, s0119, s0026, s0121, s0002, s0039, s01...","[-0.6153141, 0.07517785, -0.5039633, -0.243659...",0.105041,"[discovery, resource_development, collection, ...",0.256782
2,G0005,"[s0040, s0015, s0003]","[-0.32223642, 0.029669948, -0.7427179, -0.0198...",-0.924954,[],-0.736860
3,G0023,[s0064],"[-0.39972576, -0.06616345, -0.55075675, -0.038...",-0.924954,[],-0.736860
4,G0025,[s0069],"[-0.608141, -0.007160956, -0.7598587, 0.167140...",-0.924954,[],-0.736860
...,...,...,...,...,...,...
131,G0044,"[s0013, other]","[-0.3997315, 0.011453139, -0.5749509, -0.17962...",-0.924954,[],-0.736860
132,G0102,"[s0552, s0534, s0521, s0154, s0363, s0632, s00...","[-0.27592593, -0.100573234, -0.37286678, -0.02...",1.135036,"[discovery, collection, credential_access, com...",-0.736860
133,G0128,[],"[-0.48862642, -0.18858606, -0.5323841, -0.0883...",0.239388,"[resource_development, resource_development, p...",0.380987
134,G0018,"[s0039, s0012, s0096, s0100, s0104, other]","[-0.2925966, 0.0350828, -0.64397854, 0.130665,...",-0.387565,"[discovery, execution, execution, discovery, d...",-0.240039
135,G0045,"[s0552, s0154, s0357, s0002, s0039, s0097, s00...","[-0.73226637, -0.113698326, -1.0054364, -0.120...",1.179819,"[discovery, resource_development, collection, ...",1.643741

In [29]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Your normalized values
normalized_values = np.array([[0.5, 1.0, 1.5],
                              [2.0, 2.5, 3.0],
                              [3.5, 4.0, 4.5]])

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to your normalized data
scaler.fit(normalized_values)

# Use inverse_transform to get the original values
original_values = scaler.inverse_transform(normalized_values)

print("Original Values:")
print(original_values)

Original Values:
[[2.61237244 3.72474487 4.83711731]
 [4.44948974 5.56186218 6.67423461]
 [6.28660705 7.39897949 8.51135192]]